version: "3.9"
services:
  graph:
    image: "neo4j:4.3.6-community"
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/dfr4223dDWEFF4456SF
  app:
    build: .
    container_name: api
    restart: always
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - graph
